### ISSUE TITLE
Distroless

### ISSUE THREAD

**Issue by smorimoto** [fly-apps/dockerfile-node#18]
It would be better to be able to support distroless Node.js images as an option: https://github.com/GoogleContainerTools/distroless

**Comment by rubys** [comment]
I've added a [distroless option](https://github.com/fly-apps/dockerfile-node/commit/0e98afb141ee935c70d3916d98ae0af4d5669953).  Notes:

  * Node version must be 16 or higher and even.  Point releases aren't available, so you get what you get.
  * No shell means no entrypoint script.  Entrypoint scripts are currently emitted for prisma migrations and swapfiles.  A follow-on effort will be to rewrite these scripts in node so that they can be run distroless too.
  * No npm means no `npm run start`.  Instead the start command is extracted from the `package.json` and run.  If that command starts with `node`, that first token is stripped from the command.  It also means no `&&` or `;` running multiple commands or redirection features provided by the shell.

I'm fine with this being an option.  Those that chose the option may need to make some adjustments.  If those adjustments don't work out, they can always revert.

Feel free to reopen this issue (or open a new issue) if more is desired.
