### ISSUE TITLE
Support for Remix Blues stack

### ISSUE THREAD

**Issue by MichaelDeBoey** [fly-apps/dockerfile-node#41]
https://github.com/remix-run/blues-stack

Things I can immediately think of:
- PostgreSQL (instead of SQLite in indie-stack)
- multi-region

**Comment by MichaelDeBoey** [comment]
@rubys fcadfe9 only fixed PostgreSQL support I think

Do we also want to set all multi-region related things?
Or is that not possible in a generic way you think?

**Comment by rubys** [comment]
Can you enumerate what you mean by "all multi-region related things".

For blues stack, I removed the need for the dockerfile-endpoint script - migration and even swap can be done by the `fly.toml`, and will be done once per deploy instead of once per region.

Once deployed, spinning up new machines in other regions can be done with `fly machine clone` and/or `fly scale` commands.

**Comment by MichaelDeBoey** [comment]
@rubys The `blues-stack`'s `README` file [mentions](https://github.com/remix-run/blues-stack#multi-region-deploys) setting `PRIMARY_REGION`

This could however already be outdated information though 🤔

> Once you have your site and database running in a single region, you can add more regions by following [Fly's Scaling](https://fly.io/docs/reference/scaling/) and [Multi-region PostgreSQL](https://fly.io/docs/getting-started/multi-region-databases/) docs.

Make certain to set a `PRIMARY_REGION` environment variable for your app. You can use `[env]` config in the `fly.toml` to set that to the region you want to use as the primary region for both your app and database.

**Comment by rubys** [comment]
`PRIMARY_REGION` will automatically be set for you.

**Comment by rubys** [comment]
released: flyctl v0.1.68 and @flydotio/dockerfile@0.4.1 contain these changes.
